# compiler flags:
#  -g    adds debugging information to the executable file
#  -Wall turns on most, but not all, compiler warnings
CFLAGS=-Wall -g

all: logfind_1
	./logfind_1 || true
	./logfind_1 word1 test