# compiler flags:
#  -g    adds debugging information to the executable file
#  -Wall turns on most, but not all, compiler warnings

ex22_main: ex22_main.c ex22.c
	cc -o ex22_main ex22_main.c ex22.c